### ISSUE TITLE
This is not even a broadcasting code neither it works

### ISSUE THREAD

**Issue by sudeepigntion** [gswly/howto-udp-broadcast-golang#1]
In cast of broadcasting the client has to write to an IP and port. In golang there is method called writeToUDP

**Comment by aler9** [comment]
Hello, i don't understand what you mean, your message is very generic and doesn't say much about the problem or how to solve it. You mention "an IP and port", and in all examples provided there's an IP and port, in fact there are two IPs (the source one and the destination one) and a single, broadcast port. You mention UDPConn.WriteToUDP(), that in any case is called by WriteTo(), is just a lower level function. No other informations are provided, so this issue is a waste of time for both me and you.

I wrote this small tutorial over a year ago, so it can be outdated or full of defects, you're free to try it (as many others did and thanked me) or to suggest a better way to address the UDP broadcast problem. Posting rude or incomplete message doesn't encourage collaboration, which is essential if you want to contribute to the open source world and receive contributes from it.
